"""Pronóstico temporal determinista, solo con stdlib, sobre ventas observadas.

Los objetivos son ``observed_sales = sale_amount`` — ventas de la fuente
observadas, posiblemente censuradas, nunca etiquetadas como demanda real
(``latent_demand_estimate`` es siempre ``None``). Módulos públicos: ``splits``,
``targets``, ``baselines``, ``metrics``, ``evaluation``.
"""

from inventory_optimizer.forecasting.baselines import (
    BASELINES,
    BaselineError,
    BaselineForecastResult,
    ForecastRow,
    REASON_NO_HISTORY,
    REASON_NO_SEASONAL_LAG,
    TargetNotInFutureError,
    fit_baseline,
    fit_moving_average,
    fit_naive,
    fit_seasonal_naive,
    fit_ses,
)
from inventory_optimizer.forecasting.evaluation import (
    EVALUATION_PARTITIONS,
    EVALUATION_PARTITION_TEST,
    EVALUATION_PARTITION_VALIDATION,
    EVALUATION_PROTOCOL_VERSION,
    BaselineEvaluationConfig,
    EvaluationConfig,
    EvaluationPartition,
    EvaluationProtocol,
    EvaluationReport,
    EvaluationResult,
    EvaluationSplitConfig,
    FIT_PARTITION_TRAIN,
    FIT_PARTITION_TRAIN_PLUS_VALIDATION,
    FoldEvaluationConfig,
    FoldEvaluationStatus,
    REQUIRED_MODEL_ORDER,
    run_baseline_evaluation,
)
from inventory_optimizer.forecasting.metrics import (
    WMAPE_CALCULABLE,
    WMAPE_NO_EVALUABLE,
    WMAPE_ZERO_ACTUALS,
    ForecastMetrics,
    evaluate_metrics,
)
from inventory_optimizer.forecasting.splits import (
    DuplicateKeyError,
    ExpandingWindowFold,
    InsufficientHistory,
    InvalidBoundaryOrderError,
    MissingDatesForProduct,
    SplittingError,
    TemporalSplit,
    expanding_window_folds,
    split_temporal,
)
from inventory_optimizer.forecasting.targets import (
    ObservationState,
    TargetRow,
    project_targets,
)

__all__ = [
    "BASELINES",
    "BaselineError",
    "BaselineEvaluationConfig",
    "BaselineForecastResult",
    "DuplicateKeyError",
    "EVALUATION_PARTITIONS",
    "EVALUATION_PARTITION_TEST",
    "EVALUATION_PARTITION_VALIDATION",
    "EVALUATION_PROTOCOL_VERSION",
    "EvaluationConfig",
    "EvaluationPartition",
    "EvaluationProtocol",
    "EvaluationReport",
    "EvaluationResult",
    "EvaluationSplitConfig",
    "ExpandingWindowFold",
    "FIT_PARTITION_TRAIN",
    "FIT_PARTITION_TRAIN_PLUS_VALIDATION",
    "ForecastMetrics",
    "FoldEvaluationConfig",
    "FoldEvaluationStatus",
    "ForecastRow",
    "InsufficientHistory",
    "InvalidBoundaryOrderError",
    "MissingDatesForProduct",
    "ObservationState",
    "REASON_NO_HISTORY",
    "REASON_NO_SEASONAL_LAG",
    "REQUIRED_MODEL_ORDER",
    "SplittingError",
    "TargetNotInFutureError",
    "TargetRow",
    "TemporalSplit",
    "WMAPE_CALCULABLE",
    "WMAPE_NO_EVALUABLE",
    "WMAPE_ZERO_ACTUALS",
    "evaluate_metrics",
    "expanding_window_folds",
    "fit_baseline",
    "fit_moving_average",
    "fit_naive",
    "fit_seasonal_naive",
    "fit_ses",
    "project_targets",
    "run_baseline_evaluation",
    "split_temporal",
]
